# Generated by Django 4.1.7 on 2023-04-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentalResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentalResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentalResearchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('price', models.PositiveIntegerField()),
                ('interesting_fact', models.CharField(default='', max_length=2000)),
                ('i_r', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.instrumentalresearch')),
                ('preparations', models.ManyToManyField(to='mainapp.preparation')),
            ],
        ),
        migrations.AddField(
            model_name='instrumentalresearch',
            name='i_r_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.instrumentalresearchcategory'),
        ),
    ]
