# Generated by Django 4.2 on 2023-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_instrumentalresearchcard_instrumental_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentalresearchcard',
            name='i_r_interesting_fact',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
